// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.unto.twitter;

public final class TwitterProtos {
  private TwitterProtos() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\rtwitter.proto\022\007twitter\"\254\004\n\004User\022\n\n\002id\030" +
      "\001 \001(\004\022\014\n\004name\030\002 \001(\t\022\023\n\013screen_name\030\003 \001(\t" +
      "\022\020\n\010location\030\004 \001(\t\022\023\n\013description\030\005 \001(\t\022" +
      "&\n\007profile\030\006 \001(\0132\025.twitter.User.Profile\022" +
      "\013\n\003url\030\007 \001(\t\022\021\n\tprotected\030\010 \001(\010\022\027\n\017follo" +
      "wers_count\030\t \001(\r\022\025\n\rfriends_count\030\n \001(\r\022" +
      "\022\n\ncreated_at\030\013 \001(\t\022\027\n\017favorites_count\030\014" +
      " \001(\r\022\022\n\nutc_offset\030\r \001(\021\022\021\n\ttime_zone\030\016 " +
      "\001(\t\022\021\n\tfollowing\030\017 \001(\010\022\025\n\rnotifications\030" +
      "\020 \001(\010\022\032\n\022total_status_count\030\021 \001(\r\022!\n\010sta" +
      "tuses\030\022 \003(\0132\017.twitter.Status\032\230\001\n\007Profile" +
      "\022\021\n\timage_url\030\001 \001(\t\022\030\n\020background_color\030" +
      "\002 \001(\t\022\022\n\ntext_color\030\003 \001(\t\022\022\n\nlink_color\030" +
      "\004 \001(\t\022\032\n\022sidebar_fill_color\030\005 \001(\t\022\034\n\024sid" +
      "ebar_border_color\030\006 \001(\t\"\305\001\n\006Status\022\022\n\ncr" +
      "eated_at\030\001 \001(\t\022\n\n\002id\030\002 \001(\004\022\014\n\004text\030\003 \001(\t" +
      "\022\016\n\006source\030\004 \001(\t\022\021\n\ttruncated\030\005 \001(\010\022\035\n\025i" +
      "n_reply_to_status_id\030\006 \001(\004\022\033\n\023in_reply_t" +
      "o_user_id\030\007 \001(\004\022\021\n\tfavorited\030\010 \001(\010\022\033\n\004us" +
      "er\030\t \001(\0132\r.twitter.User\"\342\001\n\rDirectMessag" +
      "e\022\n\n\002id\030\001 \001(\004\022\014\n\004text\030\002 \001(\t\022\021\n\tsender_id" +
      "\030\003 \001(\004\022\024\n\014recipient_id\030\004 \001(\004\022\022\n\ncreated_" +
      "at\030\005 \001(\t\022\032\n\022sender_screen_name\030\006 \001(\t\022\035\n\025" +
      "recipient_screen_name\030\007 \001(\t\022\035\n\006sender\030\010 " +
      "\001(\0132\r.twitter.User\022 \n\trecipient\030\t \001(\0132\r." +
      "twitter.UserB!\n\020net.unto.twitterB\rTwitte" +
      "rProtos";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"twitter.proto\".", e);
    }
  }
  
  public static final class User extends
      com.google.protobuf.GeneratedMessage {
    // Use User.newBuilder() to construct.
    private User() {}
    
    private static final User defaultInstance = new User();
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.unto.twitter.TwitterProtos.internal_static_twitter_User_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.unto.twitter.TwitterProtos.internal_static_twitter_User_fieldAccessorTable;
    }
    
    public static final class Profile extends
        com.google.protobuf.GeneratedMessage {
      // Use Profile.newBuilder() to construct.
      private Profile() {}
      
      private static final Profile defaultInstance = new Profile();
      public static Profile getDefaultInstance() {
        return defaultInstance;
      }
      
      public Profile getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.unto.twitter.TwitterProtos.internal_static_twitter_User_Profile_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.unto.twitter.TwitterProtos.internal_static_twitter_User_Profile_fieldAccessorTable;
      }
      
      // optional string image_url = 1;
      private boolean hasImageUrl;
      private java.lang.String imageUrl_ = "";
      public boolean hasImageUrl() { return hasImageUrl; }
      public java.lang.String getImageUrl() { return imageUrl_; }
      
      // optional string background_color = 2;
      private boolean hasBackgroundColor;
      private java.lang.String backgroundColor_ = "";
      public boolean hasBackgroundColor() { return hasBackgroundColor; }
      public java.lang.String getBackgroundColor() { return backgroundColor_; }
      
      // optional string text_color = 3;
      private boolean hasTextColor;
      private java.lang.String textColor_ = "";
      public boolean hasTextColor() { return hasTextColor; }
      public java.lang.String getTextColor() { return textColor_; }
      
      // optional string link_color = 4;
      private boolean hasLinkColor;
      private java.lang.String linkColor_ = "";
      public boolean hasLinkColor() { return hasLinkColor; }
      public java.lang.String getLinkColor() { return linkColor_; }
      
      // optional string sidebar_fill_color = 5;
      private boolean hasSidebarFillColor;
      private java.lang.String sidebarFillColor_ = "";
      public boolean hasSidebarFillColor() { return hasSidebarFillColor; }
      public java.lang.String getSidebarFillColor() { return sidebarFillColor_; }
      
      // optional string sidebar_border_color = 6;
      private boolean hasSidebarBorderColor;
      private java.lang.String sidebarBorderColor_ = "";
      public boolean hasSidebarBorderColor() { return hasSidebarBorderColor; }
      public java.lang.String getSidebarBorderColor() { return sidebarBorderColor_; }
      
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.unto.twitter.TwitterProtos.User.Profile parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return new Builder(); }
      public static Builder newBuilder(net.unto.twitter.TwitterProtos.User.Profile prototype) {
        return new Builder().mergeFrom(prototype);
      }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        // Construct using net.unto.twitter.TwitterProtos.User.Profile.newBuilder()
        private Builder() {}
        
        net.unto.twitter.TwitterProtos.User.Profile result = new net.unto.twitter.TwitterProtos.User.Profile();
        
        protected net.unto.twitter.TwitterProtos.User.Profile internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          result = new net.unto.twitter.TwitterProtos.User.Profile();
          return this;
        }
        
        public Builder clone() {
          return new Builder().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.unto.twitter.TwitterProtos.User.Profile.getDescriptor();
        }
        
        public net.unto.twitter.TwitterProtos.User.Profile getDefaultInstanceForType() {
          return net.unto.twitter.TwitterProtos.User.Profile.getDefaultInstance();
        }
        
        public net.unto.twitter.TwitterProtos.User.Profile build() {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result);
          }
          return buildPartial();
        }
        
        private net.unto.twitter.TwitterProtos.User.Profile buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public net.unto.twitter.TwitterProtos.User.Profile buildPartial() {
          net.unto.twitter.TwitterProtos.User.Profile returnMe = result;
          result = null;
          return returnMe;
        }
        
        
        // optional string image_url = 1;
        public boolean hasImageUrl() {
          return result.hasImageUrl();
        }
        public java.lang.String getImageUrl() {
          return result.getImageUrl();
        }
        public Builder setImageUrl(java.lang.String value) {
          result.hasImageUrl = true;
          result.imageUrl_ = value;
          return this;
        }
        public Builder clearImageUrl() {
          result.hasImageUrl = false;
          result.imageUrl_ = "";
          return this;
        }
        
        // optional string background_color = 2;
        public boolean hasBackgroundColor() {
          return result.hasBackgroundColor();
        }
        public java.lang.String getBackgroundColor() {
          return result.getBackgroundColor();
        }
        public Builder setBackgroundColor(java.lang.String value) {
          result.hasBackgroundColor = true;
          result.backgroundColor_ = value;
          return this;
        }
        public Builder clearBackgroundColor() {
          result.hasBackgroundColor = false;
          result.backgroundColor_ = "";
          return this;
        }
        
        // optional string text_color = 3;
        public boolean hasTextColor() {
          return result.hasTextColor();
        }
        public java.lang.String getTextColor() {
          return result.getTextColor();
        }
        public Builder setTextColor(java.lang.String value) {
          result.hasTextColor = true;
          result.textColor_ = value;
          return this;
        }
        public Builder clearTextColor() {
          result.hasTextColor = false;
          result.textColor_ = "";
          return this;
        }
        
        // optional string link_color = 4;
        public boolean hasLinkColor() {
          return result.hasLinkColor();
        }
        public java.lang.String getLinkColor() {
          return result.getLinkColor();
        }
        public Builder setLinkColor(java.lang.String value) {
          result.hasLinkColor = true;
          result.linkColor_ = value;
          return this;
        }
        public Builder clearLinkColor() {
          result.hasLinkColor = false;
          result.linkColor_ = "";
          return this;
        }
        
        // optional string sidebar_fill_color = 5;
        public boolean hasSidebarFillColor() {
          return result.hasSidebarFillColor();
        }
        public java.lang.String getSidebarFillColor() {
          return result.getSidebarFillColor();
        }
        public Builder setSidebarFillColor(java.lang.String value) {
          result.hasSidebarFillColor = true;
          result.sidebarFillColor_ = value;
          return this;
        }
        public Builder clearSidebarFillColor() {
          result.hasSidebarFillColor = false;
          result.sidebarFillColor_ = "";
          return this;
        }
        
        // optional string sidebar_border_color = 6;
        public boolean hasSidebarBorderColor() {
          return result.hasSidebarBorderColor();
        }
        public java.lang.String getSidebarBorderColor() {
          return result.getSidebarBorderColor();
        }
        public Builder setSidebarBorderColor(java.lang.String value) {
          result.hasSidebarBorderColor = true;
          result.sidebarBorderColor_ = value;
          return this;
        }
        public Builder clearSidebarBorderColor() {
          result.hasSidebarBorderColor = false;
          result.sidebarBorderColor_ = "";
          return this;
        }
      }
    }
    
    // optional uint64 id = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // optional string name = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string screen_name = 3;
    private boolean hasScreenName;
    private java.lang.String screenName_ = "";
    public boolean hasScreenName() { return hasScreenName; }
    public java.lang.String getScreenName() { return screenName_; }
    
    // optional string location = 4;
    private boolean hasLocation;
    private java.lang.String location_ = "";
    public boolean hasLocation() { return hasLocation; }
    public java.lang.String getLocation() { return location_; }
    
    // optional string description = 5;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional .twitter.User.Profile profile = 6;
    private boolean hasProfile;
    private net.unto.twitter.TwitterProtos.User.Profile profile_ = net.unto.twitter.TwitterProtos.User.Profile.getDefaultInstance();
    public boolean hasProfile() { return hasProfile; }
    public net.unto.twitter.TwitterProtos.User.Profile getProfile() { return profile_; }
    
    // optional string url = 7;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    // optional bool protected = 8;
    private boolean hasProtected;
    private boolean protected_ = false;
    public boolean hasProtected() { return hasProtected; }
    public boolean getProtected() { return protected_; }
    
    // optional uint32 followers_count = 9;
    private boolean hasFollowersCount;
    private int followersCount_ = 0;
    public boolean hasFollowersCount() { return hasFollowersCount; }
    public int getFollowersCount() { return followersCount_; }
    
    // optional uint32 friends_count = 10;
    private boolean hasFriendsCount;
    private int friendsCount_ = 0;
    public boolean hasFriendsCount() { return hasFriendsCount; }
    public int getFriendsCount() { return friendsCount_; }
    
    // optional string created_at = 11;
    private boolean hasCreatedAt;
    private java.lang.String createdAt_ = "";
    public boolean hasCreatedAt() { return hasCreatedAt; }
    public java.lang.String getCreatedAt() { return createdAt_; }
    
    // optional uint32 favorites_count = 12;
    private boolean hasFavoritesCount;
    private int favoritesCount_ = 0;
    public boolean hasFavoritesCount() { return hasFavoritesCount; }
    public int getFavoritesCount() { return favoritesCount_; }
    
    // optional sint32 utc_offset = 13;
    private boolean hasUtcOffset;
    private int utcOffset_ = 0;
    public boolean hasUtcOffset() { return hasUtcOffset; }
    public int getUtcOffset() { return utcOffset_; }
    
    // optional string time_zone = 14;
    private boolean hasTimeZone;
    private java.lang.String timeZone_ = "";
    public boolean hasTimeZone() { return hasTimeZone; }
    public java.lang.String getTimeZone() { return timeZone_; }
    
    // optional bool following = 15;
    private boolean hasFollowing;
    private boolean following_ = false;
    public boolean hasFollowing() { return hasFollowing; }
    public boolean getFollowing() { return following_; }
    
    // optional bool notifications = 16;
    private boolean hasNotifications;
    private boolean notifications_ = false;
    public boolean hasNotifications() { return hasNotifications; }
    public boolean getNotifications() { return notifications_; }
    
    // optional uint32 total_status_count = 17;
    private boolean hasTotalStatusCount;
    private int totalStatusCount_ = 0;
    public boolean hasTotalStatusCount() { return hasTotalStatusCount; }
    public int getTotalStatusCount() { return totalStatusCount_; }
    
    // repeated .twitter.Status statuses = 18;
    private java.util.List<net.unto.twitter.TwitterProtos.Status> statuses_ =
      java.util.Collections.emptyList();
    public java.util.List<net.unto.twitter.TwitterProtos.Status> getStatusesList() {
      return statuses_;
    }
    public int getStatusesCount() { return statuses_.size(); }
    public net.unto.twitter.TwitterProtos.Status getStatuses(int index) {
      return statuses_.get(index);
    }
    
    public static net.unto.twitter.TwitterProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.unto.twitter.TwitterProtos.User prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.unto.twitter.TwitterProtos.User.newBuilder()
      private Builder() {}
      
      net.unto.twitter.TwitterProtos.User result = new net.unto.twitter.TwitterProtos.User();
      
      protected net.unto.twitter.TwitterProtos.User internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.unto.twitter.TwitterProtos.User();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.unto.twitter.TwitterProtos.User.getDescriptor();
      }
      
      public net.unto.twitter.TwitterProtos.User getDefaultInstanceForType() {
        return net.unto.twitter.TwitterProtos.User.getDefaultInstance();
      }
      
      public net.unto.twitter.TwitterProtos.User build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.unto.twitter.TwitterProtos.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.unto.twitter.TwitterProtos.User buildPartial() {
        if (result.statuses_ != java.util.Collections.EMPTY_LIST) {
          result.statuses_ =
            java.util.Collections.unmodifiableList(result.statuses_);
        }
        net.unto.twitter.TwitterProtos.User returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional string screen_name = 3;
      public boolean hasScreenName() {
        return result.hasScreenName();
      }
      public java.lang.String getScreenName() {
        return result.getScreenName();
      }
      public Builder setScreenName(java.lang.String value) {
        result.hasScreenName = true;
        result.screenName_ = value;
        return this;
      }
      public Builder clearScreenName() {
        result.hasScreenName = false;
        result.screenName_ = "";
        return this;
      }
      
      // optional string location = 4;
      public boolean hasLocation() {
        return result.hasLocation();
      }
      public java.lang.String getLocation() {
        return result.getLocation();
      }
      public Builder setLocation(java.lang.String value) {
        result.hasLocation = true;
        result.location_ = value;
        return this;
      }
      public Builder clearLocation() {
        result.hasLocation = false;
        result.location_ = "";
        return this;
      }
      
      // optional string description = 5;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = "";
        return this;
      }
      
      // optional .twitter.User.Profile profile = 6;
      public boolean hasProfile() {
        return result.hasProfile();
      }
      public net.unto.twitter.TwitterProtos.User.Profile getProfile() {
        return result.getProfile();
      }
      public Builder setProfile(net.unto.twitter.TwitterProtos.User.Profile value) {
        result.hasProfile = true;
        result.profile_ = value;
        return this;
      }
      public Builder setProfile(net.unto.twitter.TwitterProtos.User.Profile.Builder builderForValue) {
        result.hasProfile = true;
        result.profile_ = builderForValue.build();
        return this;
      }
      public Builder mergeProfile(net.unto.twitter.TwitterProtos.User.Profile value) {
        if (result.hasProfile() &&
            result.profile_ != net.unto.twitter.TwitterProtos.User.Profile.getDefaultInstance()) {
          result.profile_ =
            net.unto.twitter.TwitterProtos.User.Profile.newBuilder(result.profile_).mergeFrom(value).buildPartial();
        } else {
          result.profile_ = value;
        }
        result.hasProfile = true;
        return this;
      }
      public Builder clearProfile() {
        result.hasProfile = false;
        result.profile_ = net.unto.twitter.TwitterProtos.User.Profile.getDefaultInstance();
        return this;
      }
      
      // optional string url = 7;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = "";
        return this;
      }
      
      // optional bool protected = 8;
      public boolean hasProtected() {
        return result.hasProtected();
      }
      public boolean getProtected() {
        return result.getProtected();
      }
      public Builder setProtected(boolean value) {
        result.hasProtected = true;
        result.protected_ = value;
        return this;
      }
      public Builder clearProtected() {
        result.hasProtected = false;
        result.protected_ = false;
        return this;
      }
      
      // optional uint32 followers_count = 9;
      public boolean hasFollowersCount() {
        return result.hasFollowersCount();
      }
      public int getFollowersCount() {
        return result.getFollowersCount();
      }
      public Builder setFollowersCount(int value) {
        result.hasFollowersCount = true;
        result.followersCount_ = value;
        return this;
      }
      public Builder clearFollowersCount() {
        result.hasFollowersCount = false;
        result.followersCount_ = 0;
        return this;
      }
      
      // optional uint32 friends_count = 10;
      public boolean hasFriendsCount() {
        return result.hasFriendsCount();
      }
      public int getFriendsCount() {
        return result.getFriendsCount();
      }
      public Builder setFriendsCount(int value) {
        result.hasFriendsCount = true;
        result.friendsCount_ = value;
        return this;
      }
      public Builder clearFriendsCount() {
        result.hasFriendsCount = false;
        result.friendsCount_ = 0;
        return this;
      }
      
      // optional string created_at = 11;
      public boolean hasCreatedAt() {
        return result.hasCreatedAt();
      }
      public java.lang.String getCreatedAt() {
        return result.getCreatedAt();
      }
      public Builder setCreatedAt(java.lang.String value) {
        result.hasCreatedAt = true;
        result.createdAt_ = value;
        return this;
      }
      public Builder clearCreatedAt() {
        result.hasCreatedAt = false;
        result.createdAt_ = "";
        return this;
      }
      
      // optional uint32 favorites_count = 12;
      public boolean hasFavoritesCount() {
        return result.hasFavoritesCount();
      }
      public int getFavoritesCount() {
        return result.getFavoritesCount();
      }
      public Builder setFavoritesCount(int value) {
        result.hasFavoritesCount = true;
        result.favoritesCount_ = value;
        return this;
      }
      public Builder clearFavoritesCount() {
        result.hasFavoritesCount = false;
        result.favoritesCount_ = 0;
        return this;
      }
      
      // optional sint32 utc_offset = 13;
      public boolean hasUtcOffset() {
        return result.hasUtcOffset();
      }
      public int getUtcOffset() {
        return result.getUtcOffset();
      }
      public Builder setUtcOffset(int value) {
        result.hasUtcOffset = true;
        result.utcOffset_ = value;
        return this;
      }
      public Builder clearUtcOffset() {
        result.hasUtcOffset = false;
        result.utcOffset_ = 0;
        return this;
      }
      
      // optional string time_zone = 14;
      public boolean hasTimeZone() {
        return result.hasTimeZone();
      }
      public java.lang.String getTimeZone() {
        return result.getTimeZone();
      }
      public Builder setTimeZone(java.lang.String value) {
        result.hasTimeZone = true;
        result.timeZone_ = value;
        return this;
      }
      public Builder clearTimeZone() {
        result.hasTimeZone = false;
        result.timeZone_ = "";
        return this;
      }
      
      // optional bool following = 15;
      public boolean hasFollowing() {
        return result.hasFollowing();
      }
      public boolean getFollowing() {
        return result.getFollowing();
      }
      public Builder setFollowing(boolean value) {
        result.hasFollowing = true;
        result.following_ = value;
        return this;
      }
      public Builder clearFollowing() {
        result.hasFollowing = false;
        result.following_ = false;
        return this;
      }
      
      // optional bool notifications = 16;
      public boolean hasNotifications() {
        return result.hasNotifications();
      }
      public boolean getNotifications() {
        return result.getNotifications();
      }
      public Builder setNotifications(boolean value) {
        result.hasNotifications = true;
        result.notifications_ = value;
        return this;
      }
      public Builder clearNotifications() {
        result.hasNotifications = false;
        result.notifications_ = false;
        return this;
      }
      
      // optional uint32 total_status_count = 17;
      public boolean hasTotalStatusCount() {
        return result.hasTotalStatusCount();
      }
      public int getTotalStatusCount() {
        return result.getTotalStatusCount();
      }
      public Builder setTotalStatusCount(int value) {
        result.hasTotalStatusCount = true;
        result.totalStatusCount_ = value;
        return this;
      }
      public Builder clearTotalStatusCount() {
        result.hasTotalStatusCount = false;
        result.totalStatusCount_ = 0;
        return this;
      }
      
      // repeated .twitter.Status statuses = 18;
      public java.util.List<net.unto.twitter.TwitterProtos.Status> getStatusesList() {
        return java.util.Collections.unmodifiableList(result.statuses_);
      }
      public int getStatusesCount() {
        return result.getStatusesCount();
      }
      public net.unto.twitter.TwitterProtos.Status getStatuses(int index) {
        return result.getStatuses(index);
      }
      public Builder setStatuses(int index, net.unto.twitter.TwitterProtos.Status value) {
        result.statuses_.set(index, value);
        return this;
      }
      public Builder setStatuses(int index, net.unto.twitter.TwitterProtos.Status.Builder builderForValue) {
        result.statuses_.set(index, builderForValue.build());
        return this;
      }
      public Builder addStatuses(net.unto.twitter.TwitterProtos.Status value) {
        if (result.statuses_.isEmpty()) {
          result.statuses_ = new java.util.ArrayList<net.unto.twitter.TwitterProtos.Status>();
        }
        result.statuses_.add(value);
        return this;
      }
      public Builder addStatuses(net.unto.twitter.TwitterProtos.Status.Builder builderForValue) {
        if (result.statuses_.isEmpty()) {
          result.statuses_ = new java.util.ArrayList<net.unto.twitter.TwitterProtos.Status>();
        }
        result.statuses_.add(builderForValue.build());
        return this;
      }
      public Builder addAllStatuses(
          java.lang.Iterable<? extends net.unto.twitter.TwitterProtos.Status> values) {
        if (result.statuses_.isEmpty()) {
          result.statuses_ = new java.util.ArrayList<net.unto.twitter.TwitterProtos.Status>();
        }
        super.addAll(values, result.statuses_);
        return this;
      }
      public Builder clearStatuses() {
        result.statuses_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class Status extends
      com.google.protobuf.GeneratedMessage {
    // Use Status.newBuilder() to construct.
    private Status() {}
    
    private static final Status defaultInstance = new Status();
    public static Status getDefaultInstance() {
      return defaultInstance;
    }
    
    public Status getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.unto.twitter.TwitterProtos.internal_static_twitter_Status_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.unto.twitter.TwitterProtos.internal_static_twitter_Status_fieldAccessorTable;
    }
    
    // optional string created_at = 1;
    private boolean hasCreatedAt;
    private java.lang.String createdAt_ = "";
    public boolean hasCreatedAt() { return hasCreatedAt; }
    public java.lang.String getCreatedAt() { return createdAt_; }
    
    // optional uint64 id = 2;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // optional string text = 3;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    // optional string source = 4;
    private boolean hasSource;
    private java.lang.String source_ = "";
    public boolean hasSource() { return hasSource; }
    public java.lang.String getSource() { return source_; }
    
    // optional bool truncated = 5;
    private boolean hasTruncated;
    private boolean truncated_ = false;
    public boolean hasTruncated() { return hasTruncated; }
    public boolean getTruncated() { return truncated_; }
    
    // optional uint64 in_reply_to_status_id = 6;
    private boolean hasInReplyToStatusId;
    private long inReplyToStatusId_ = 0L;
    public boolean hasInReplyToStatusId() { return hasInReplyToStatusId; }
    public long getInReplyToStatusId() { return inReplyToStatusId_; }
    
    // optional uint64 in_reply_to_user_id = 7;
    private boolean hasInReplyToUserId;
    private long inReplyToUserId_ = 0L;
    public boolean hasInReplyToUserId() { return hasInReplyToUserId; }
    public long getInReplyToUserId() { return inReplyToUserId_; }
    
    // optional bool favorited = 8;
    private boolean hasFavorited;
    private boolean favorited_ = false;
    public boolean hasFavorited() { return hasFavorited; }
    public boolean getFavorited() { return favorited_; }
    
    // optional .twitter.User user = 9;
    private boolean hasUser;
    private net.unto.twitter.TwitterProtos.User user_ = net.unto.twitter.TwitterProtos.User.getDefaultInstance();
    public boolean hasUser() { return hasUser; }
    public net.unto.twitter.TwitterProtos.User getUser() { return user_; }
    
    public static net.unto.twitter.TwitterProtos.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.unto.twitter.TwitterProtos.Status prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.unto.twitter.TwitterProtos.Status.newBuilder()
      private Builder() {}
      
      net.unto.twitter.TwitterProtos.Status result = new net.unto.twitter.TwitterProtos.Status();
      
      protected net.unto.twitter.TwitterProtos.Status internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.unto.twitter.TwitterProtos.Status();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.unto.twitter.TwitterProtos.Status.getDescriptor();
      }
      
      public net.unto.twitter.TwitterProtos.Status getDefaultInstanceForType() {
        return net.unto.twitter.TwitterProtos.Status.getDefaultInstance();
      }
      
      public net.unto.twitter.TwitterProtos.Status build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.unto.twitter.TwitterProtos.Status buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.unto.twitter.TwitterProtos.Status buildPartial() {
        net.unto.twitter.TwitterProtos.Status returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string created_at = 1;
      public boolean hasCreatedAt() {
        return result.hasCreatedAt();
      }
      public java.lang.String getCreatedAt() {
        return result.getCreatedAt();
      }
      public Builder setCreatedAt(java.lang.String value) {
        result.hasCreatedAt = true;
        result.createdAt_ = value;
        return this;
      }
      public Builder clearCreatedAt() {
        result.hasCreatedAt = false;
        result.createdAt_ = "";
        return this;
      }
      
      // optional uint64 id = 2;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // optional string text = 3;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = "";
        return this;
      }
      
      // optional string source = 4;
      public boolean hasSource() {
        return result.hasSource();
      }
      public java.lang.String getSource() {
        return result.getSource();
      }
      public Builder setSource(java.lang.String value) {
        result.hasSource = true;
        result.source_ = value;
        return this;
      }
      public Builder clearSource() {
        result.hasSource = false;
        result.source_ = "";
        return this;
      }
      
      // optional bool truncated = 5;
      public boolean hasTruncated() {
        return result.hasTruncated();
      }
      public boolean getTruncated() {
        return result.getTruncated();
      }
      public Builder setTruncated(boolean value) {
        result.hasTruncated = true;
        result.truncated_ = value;
        return this;
      }
      public Builder clearTruncated() {
        result.hasTruncated = false;
        result.truncated_ = false;
        return this;
      }
      
      // optional uint64 in_reply_to_status_id = 6;
      public boolean hasInReplyToStatusId() {
        return result.hasInReplyToStatusId();
      }
      public long getInReplyToStatusId() {
        return result.getInReplyToStatusId();
      }
      public Builder setInReplyToStatusId(long value) {
        result.hasInReplyToStatusId = true;
        result.inReplyToStatusId_ = value;
        return this;
      }
      public Builder clearInReplyToStatusId() {
        result.hasInReplyToStatusId = false;
        result.inReplyToStatusId_ = 0L;
        return this;
      }
      
      // optional uint64 in_reply_to_user_id = 7;
      public boolean hasInReplyToUserId() {
        return result.hasInReplyToUserId();
      }
      public long getInReplyToUserId() {
        return result.getInReplyToUserId();
      }
      public Builder setInReplyToUserId(long value) {
        result.hasInReplyToUserId = true;
        result.inReplyToUserId_ = value;
        return this;
      }
      public Builder clearInReplyToUserId() {
        result.hasInReplyToUserId = false;
        result.inReplyToUserId_ = 0L;
        return this;
      }
      
      // optional bool favorited = 8;
      public boolean hasFavorited() {
        return result.hasFavorited();
      }
      public boolean getFavorited() {
        return result.getFavorited();
      }
      public Builder setFavorited(boolean value) {
        result.hasFavorited = true;
        result.favorited_ = value;
        return this;
      }
      public Builder clearFavorited() {
        result.hasFavorited = false;
        result.favorited_ = false;
        return this;
      }
      
      // optional .twitter.User user = 9;
      public boolean hasUser() {
        return result.hasUser();
      }
      public net.unto.twitter.TwitterProtos.User getUser() {
        return result.getUser();
      }
      public Builder setUser(net.unto.twitter.TwitterProtos.User value) {
        result.hasUser = true;
        result.user_ = value;
        return this;
      }
      public Builder setUser(net.unto.twitter.TwitterProtos.User.Builder builderForValue) {
        result.hasUser = true;
        result.user_ = builderForValue.build();
        return this;
      }
      public Builder mergeUser(net.unto.twitter.TwitterProtos.User value) {
        if (result.hasUser() &&
            result.user_ != net.unto.twitter.TwitterProtos.User.getDefaultInstance()) {
          result.user_ =
            net.unto.twitter.TwitterProtos.User.newBuilder(result.user_).mergeFrom(value).buildPartial();
        } else {
          result.user_ = value;
        }
        result.hasUser = true;
        return this;
      }
      public Builder clearUser() {
        result.hasUser = false;
        result.user_ = net.unto.twitter.TwitterProtos.User.getDefaultInstance();
        return this;
      }
    }
  }
  
  public static final class DirectMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use DirectMessage.newBuilder() to construct.
    private DirectMessage() {}
    
    private static final DirectMessage defaultInstance = new DirectMessage();
    public static DirectMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public DirectMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.unto.twitter.TwitterProtos.internal_static_twitter_DirectMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.unto.twitter.TwitterProtos.internal_static_twitter_DirectMessage_fieldAccessorTable;
    }
    
    // optional uint64 id = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // optional string text = 2;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    // optional uint64 sender_id = 3;
    private boolean hasSenderId;
    private long senderId_ = 0L;
    public boolean hasSenderId() { return hasSenderId; }
    public long getSenderId() { return senderId_; }
    
    // optional uint64 recipient_id = 4;
    private boolean hasRecipientId;
    private long recipientId_ = 0L;
    public boolean hasRecipientId() { return hasRecipientId; }
    public long getRecipientId() { return recipientId_; }
    
    // optional string created_at = 5;
    private boolean hasCreatedAt;
    private java.lang.String createdAt_ = "";
    public boolean hasCreatedAt() { return hasCreatedAt; }
    public java.lang.String getCreatedAt() { return createdAt_; }
    
    // optional string sender_screen_name = 6;
    private boolean hasSenderScreenName;
    private java.lang.String senderScreenName_ = "";
    public boolean hasSenderScreenName() { return hasSenderScreenName; }
    public java.lang.String getSenderScreenName() { return senderScreenName_; }
    
    // optional string recipient_screen_name = 7;
    private boolean hasRecipientScreenName;
    private java.lang.String recipientScreenName_ = "";
    public boolean hasRecipientScreenName() { return hasRecipientScreenName; }
    public java.lang.String getRecipientScreenName() { return recipientScreenName_; }
    
    // optional .twitter.User sender = 8;
    private boolean hasSender;
    private net.unto.twitter.TwitterProtos.User sender_ = net.unto.twitter.TwitterProtos.User.getDefaultInstance();
    public boolean hasSender() { return hasSender; }
    public net.unto.twitter.TwitterProtos.User getSender() { return sender_; }
    
    // optional .twitter.User recipient = 9;
    private boolean hasRecipient;
    private net.unto.twitter.TwitterProtos.User recipient_ = net.unto.twitter.TwitterProtos.User.getDefaultInstance();
    public boolean hasRecipient() { return hasRecipient; }
    public net.unto.twitter.TwitterProtos.User getRecipient() { return recipient_; }
    
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.TwitterProtos.DirectMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.unto.twitter.TwitterProtos.DirectMessage prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.unto.twitter.TwitterProtos.DirectMessage.newBuilder()
      private Builder() {}
      
      net.unto.twitter.TwitterProtos.DirectMessage result = new net.unto.twitter.TwitterProtos.DirectMessage();
      
      protected net.unto.twitter.TwitterProtos.DirectMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.unto.twitter.TwitterProtos.DirectMessage();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.unto.twitter.TwitterProtos.DirectMessage.getDescriptor();
      }
      
      public net.unto.twitter.TwitterProtos.DirectMessage getDefaultInstanceForType() {
        return net.unto.twitter.TwitterProtos.DirectMessage.getDefaultInstance();
      }
      
      public net.unto.twitter.TwitterProtos.DirectMessage build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.unto.twitter.TwitterProtos.DirectMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.unto.twitter.TwitterProtos.DirectMessage buildPartial() {
        net.unto.twitter.TwitterProtos.DirectMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // optional string text = 2;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = "";
        return this;
      }
      
      // optional uint64 sender_id = 3;
      public boolean hasSenderId() {
        return result.hasSenderId();
      }
      public long getSenderId() {
        return result.getSenderId();
      }
      public Builder setSenderId(long value) {
        result.hasSenderId = true;
        result.senderId_ = value;
        return this;
      }
      public Builder clearSenderId() {
        result.hasSenderId = false;
        result.senderId_ = 0L;
        return this;
      }
      
      // optional uint64 recipient_id = 4;
      public boolean hasRecipientId() {
        return result.hasRecipientId();
      }
      public long getRecipientId() {
        return result.getRecipientId();
      }
      public Builder setRecipientId(long value) {
        result.hasRecipientId = true;
        result.recipientId_ = value;
        return this;
      }
      public Builder clearRecipientId() {
        result.hasRecipientId = false;
        result.recipientId_ = 0L;
        return this;
      }
      
      // optional string created_at = 5;
      public boolean hasCreatedAt() {
        return result.hasCreatedAt();
      }
      public java.lang.String getCreatedAt() {
        return result.getCreatedAt();
      }
      public Builder setCreatedAt(java.lang.String value) {
        result.hasCreatedAt = true;
        result.createdAt_ = value;
        return this;
      }
      public Builder clearCreatedAt() {
        result.hasCreatedAt = false;
        result.createdAt_ = "";
        return this;
      }
      
      // optional string sender_screen_name = 6;
      public boolean hasSenderScreenName() {
        return result.hasSenderScreenName();
      }
      public java.lang.String getSenderScreenName() {
        return result.getSenderScreenName();
      }
      public Builder setSenderScreenName(java.lang.String value) {
        result.hasSenderScreenName = true;
        result.senderScreenName_ = value;
        return this;
      }
      public Builder clearSenderScreenName() {
        result.hasSenderScreenName = false;
        result.senderScreenName_ = "";
        return this;
      }
      
      // optional string recipient_screen_name = 7;
      public boolean hasRecipientScreenName() {
        return result.hasRecipientScreenName();
      }
      public java.lang.String getRecipientScreenName() {
        return result.getRecipientScreenName();
      }
      public Builder setRecipientScreenName(java.lang.String value) {
        result.hasRecipientScreenName = true;
        result.recipientScreenName_ = value;
        return this;
      }
      public Builder clearRecipientScreenName() {
        result.hasRecipientScreenName = false;
        result.recipientScreenName_ = "";
        return this;
      }
      
      // optional .twitter.User sender = 8;
      public boolean hasSender() {
        return result.hasSender();
      }
      public net.unto.twitter.TwitterProtos.User getSender() {
        return result.getSender();
      }
      public Builder setSender(net.unto.twitter.TwitterProtos.User value) {
        result.hasSender = true;
        result.sender_ = value;
        return this;
      }
      public Builder setSender(net.unto.twitter.TwitterProtos.User.Builder builderForValue) {
        result.hasSender = true;
        result.sender_ = builderForValue.build();
        return this;
      }
      public Builder mergeSender(net.unto.twitter.TwitterProtos.User value) {
        if (result.hasSender() &&
            result.sender_ != net.unto.twitter.TwitterProtos.User.getDefaultInstance()) {
          result.sender_ =
            net.unto.twitter.TwitterProtos.User.newBuilder(result.sender_).mergeFrom(value).buildPartial();
        } else {
          result.sender_ = value;
        }
        result.hasSender = true;
        return this;
      }
      public Builder clearSender() {
        result.hasSender = false;
        result.sender_ = net.unto.twitter.TwitterProtos.User.getDefaultInstance();
        return this;
      }
      
      // optional .twitter.User recipient = 9;
      public boolean hasRecipient() {
        return result.hasRecipient();
      }
      public net.unto.twitter.TwitterProtos.User getRecipient() {
        return result.getRecipient();
      }
      public Builder setRecipient(net.unto.twitter.TwitterProtos.User value) {
        result.hasRecipient = true;
        result.recipient_ = value;
        return this;
      }
      public Builder setRecipient(net.unto.twitter.TwitterProtos.User.Builder builderForValue) {
        result.hasRecipient = true;
        result.recipient_ = builderForValue.build();
        return this;
      }
      public Builder mergeRecipient(net.unto.twitter.TwitterProtos.User value) {
        if (result.hasRecipient() &&
            result.recipient_ != net.unto.twitter.TwitterProtos.User.getDefaultInstance()) {
          result.recipient_ =
            net.unto.twitter.TwitterProtos.User.newBuilder(result.recipient_).mergeFrom(value).buildPartial();
        } else {
          result.recipient_ = value;
        }
        result.hasRecipient = true;
        return this;
      }
      public Builder clearRecipient() {
        result.hasRecipient = false;
        result.recipient_ = net.unto.twitter.TwitterProtos.User.getDefaultInstance();
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_twitter_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_twitter_User_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_twitter_User_descriptor,
          new java.lang.String[] { "Id", "Name", "ScreenName", "Location", "Description", "Profile", "Url", "Protected", "FollowersCount", "FriendsCount", "CreatedAt", "FavoritesCount", "UtcOffset", "TimeZone", "Following", "Notifications", "TotalStatusCount", "Statuses", },
          net.unto.twitter.TwitterProtos.User.class,
          net.unto.twitter.TwitterProtos.User.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_twitter_User_Profile_descriptor =
      internal_static_twitter_User_descriptor.getNestedTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_twitter_User_Profile_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_twitter_User_Profile_descriptor,
          new java.lang.String[] { "ImageUrl", "BackgroundColor", "TextColor", "LinkColor", "SidebarFillColor", "SidebarBorderColor", },
          net.unto.twitter.TwitterProtos.User.Profile.class,
          net.unto.twitter.TwitterProtos.User.Profile.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_twitter_Status_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_twitter_Status_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_twitter_Status_descriptor,
          new java.lang.String[] { "CreatedAt", "Id", "Text", "Source", "Truncated", "InReplyToStatusId", "InReplyToUserId", "Favorited", "User", },
          net.unto.twitter.TwitterProtos.Status.class,
          net.unto.twitter.TwitterProtos.Status.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_twitter_DirectMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_twitter_DirectMessage_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_twitter_DirectMessage_descriptor,
          new java.lang.String[] { "Id", "Text", "SenderId", "RecipientId", "CreatedAt", "SenderScreenName", "RecipientScreenName", "Sender", "Recipient", },
          net.unto.twitter.TwitterProtos.DirectMessage.class,
          net.unto.twitter.TwitterProtos.DirectMessage.Builder.class);
}
