// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.unto.twitter;

public final class UtilProtos {
  private UtilProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Url extends
      com.google.protobuf.GeneratedMessage {
    // Use Url.newBuilder() to construct.
    private Url() {}
    
    private static final Url defaultInstance = new Url();
    public static Url getDefaultInstance() {
      return defaultInstance;
    }
    
    public Url getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.unto.twitter.UtilProtos.internal_static_twitter_Url_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.unto.twitter.UtilProtos.internal_static_twitter_Url_fieldAccessorTable;
    }
    
    public static final class Parameter extends
        com.google.protobuf.GeneratedMessage {
      // Use Parameter.newBuilder() to construct.
      private Parameter() {}
      
      private static final Parameter defaultInstance = new Parameter();
      public static Parameter getDefaultInstance() {
        return defaultInstance;
      }
      
      public Parameter getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.unto.twitter.UtilProtos.internal_static_twitter_Url_Parameter_descriptor;
      }
      
      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.unto.twitter.UtilProtos.internal_static_twitter_Url_Parameter_fieldAccessorTable;
      }
      
      // required string name = 1;
      private boolean hasName;
      private java.lang.String name_ = "";
      public boolean hasName() { return hasName; }
      public java.lang.String getName() { return name_; }
      
      // optional string value = 2;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.unto.twitter.UtilProtos.Url.Parameter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return new Builder(); }
      public static Builder newBuilder(net.unto.twitter.UtilProtos.Url.Parameter prototype) {
        return new Builder().mergeFrom(prototype);
      }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        // Construct using net.unto.twitter.UtilProtos.Url.Parameter.newBuilder()
        private Builder() {}
        
        net.unto.twitter.UtilProtos.Url.Parameter result = new net.unto.twitter.UtilProtos.Url.Parameter();
        
        @Override
        protected net.unto.twitter.UtilProtos.Url.Parameter internalGetResult() {
          return result;
        }
        
        @Override
        public Builder clear() {
          result = new net.unto.twitter.UtilProtos.Url.Parameter();
          return this;
        }
        
        @Override
        public Builder clone() {
          return new Builder().mergeFrom(result);
        }
        
        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.unto.twitter.UtilProtos.Url.Parameter.getDescriptor();
        }
        
        public net.unto.twitter.UtilProtos.Url.Parameter getDefaultInstanceForType() {
          return net.unto.twitter.UtilProtos.Url.Parameter.getDefaultInstance();
        }
        
        public net.unto.twitter.UtilProtos.Url.Parameter build() {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result);
          }
          return buildPartial();
        }
        
        private net.unto.twitter.UtilProtos.Url.Parameter buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public net.unto.twitter.UtilProtos.Url.Parameter buildPartial() {
          net.unto.twitter.UtilProtos.Url.Parameter returnMe = result;
          result = null;
          return returnMe;
        }
        
        
        // required string name = 1;
        public boolean hasName() {
          return result.hasName();
        }
        public java.lang.String getName() {
          return result.getName();
        }
        public Builder setName(java.lang.String value) {
          result.hasName = true;
          result.name_ = value;
          return this;
        }
        public Builder clearName() {
          result.hasName = false;
          result.name_ = "";
          return this;
        }
        
        // optional string value = 2;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = "";
          return this;
        }
      }
      
      static {
        net.unto.twitter.UtilProtos.getDescriptor();
      }
    }
    
    // required string base_url = 1;
    private boolean hasBaseUrl;
    private java.lang.String baseUrl_ = "";
    public boolean hasBaseUrl() { return hasBaseUrl; }
    public java.lang.String getBaseUrl() { return baseUrl_; }
    
    // repeated .twitter.Url.Parameter parameters = 2;
    private java.util.List<net.unto.twitter.UtilProtos.Url.Parameter> parameters_ =
      java.util.Collections.emptyList();
    public java.util.List<net.unto.twitter.UtilProtos.Url.Parameter> getParametersList() {
      return parameters_;
    }
    public int getParametersCount() { return parameters_.size(); }
    public net.unto.twitter.UtilProtos.Url.Parameter getParameters(int index) {
      return parameters_.get(index);
    }
    
    public static net.unto.twitter.UtilProtos.Url parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.UtilProtos.Url parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.UtilProtos.Url parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.unto.twitter.UtilProtos.Url parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.UtilProtos.Url parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.UtilProtos.Url parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.unto.twitter.UtilProtos.Url parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.unto.twitter.UtilProtos.Url parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.unto.twitter.UtilProtos.Url prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.unto.twitter.UtilProtos.Url.newBuilder()
      private Builder() {}
      
      net.unto.twitter.UtilProtos.Url result = new net.unto.twitter.UtilProtos.Url();
      
      @Override
      protected net.unto.twitter.UtilProtos.Url internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.unto.twitter.UtilProtos.Url();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.unto.twitter.UtilProtos.Url.getDescriptor();
      }
      
      public net.unto.twitter.UtilProtos.Url getDefaultInstanceForType() {
        return net.unto.twitter.UtilProtos.Url.getDefaultInstance();
      }
      
      public net.unto.twitter.UtilProtos.Url build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.unto.twitter.UtilProtos.Url buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.unto.twitter.UtilProtos.Url buildPartial() {
        if (result.parameters_ != java.util.Collections.EMPTY_LIST) {
          result.parameters_ =
            java.util.Collections.unmodifiableList(result.parameters_);
        }
        net.unto.twitter.UtilProtos.Url returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string base_url = 1;
      public boolean hasBaseUrl() {
        return result.hasBaseUrl();
      }
      public java.lang.String getBaseUrl() {
        return result.getBaseUrl();
      }
      public Builder setBaseUrl(java.lang.String value) {
        result.hasBaseUrl = true;
        result.baseUrl_ = value;
        return this;
      }
      public Builder clearBaseUrl() {
        result.hasBaseUrl = false;
        result.baseUrl_ = "";
        return this;
      }
      
      // repeated .twitter.Url.Parameter parameters = 2;
      public java.util.List<net.unto.twitter.UtilProtos.Url.Parameter> getParametersList() {
        return java.util.Collections.unmodifiableList(result.parameters_);
      }
      public int getParametersCount() {
        return result.getParametersCount();
      }
      public net.unto.twitter.UtilProtos.Url.Parameter getParameters(int index) {
        return result.getParameters(index);
      }
      public Builder setParameters(int index, net.unto.twitter.UtilProtos.Url.Parameter value) {
        result.parameters_.set(index, value);
        return this;
      }
      public Builder setParameters(int index, net.unto.twitter.UtilProtos.Url.Parameter.Builder builderForValue) {
        result.parameters_.set(index, builderForValue.build());
        return this;
      }
      public Builder addParameters(net.unto.twitter.UtilProtos.Url.Parameter value) {
        if (result.parameters_.isEmpty()) {
          result.parameters_ = new java.util.ArrayList<net.unto.twitter.UtilProtos.Url.Parameter>();
        }
        result.parameters_.add(value);
        return this;
      }
      public Builder addParameters(net.unto.twitter.UtilProtos.Url.Parameter.Builder builderForValue) {
        if (result.parameters_.isEmpty()) {
          result.parameters_ = new java.util.ArrayList<net.unto.twitter.UtilProtos.Url.Parameter>();
        }
        result.parameters_.add(builderForValue.build());
        return this;
      }
      public Builder addAllParameters(
          java.lang.Iterable<? extends net.unto.twitter.UtilProtos.Url.Parameter> values) {
        if (result.parameters_.isEmpty()) {
          result.parameters_ = new java.util.ArrayList<net.unto.twitter.UtilProtos.Url.Parameter>();
        }
        super.addAll(values, result.parameters_);
        return this;
      }
      public Builder clearParameters() {
        result.parameters_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.unto.twitter.UtilProtos.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_twitter_Url_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_twitter_Url_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_twitter_Url_Parameter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_twitter_Url_Parameter_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\nutil.proto\022\007twitter\"m\n\003Url\022\020\n\010base_url" +
      "\030\001 \002(\t\022*\n\nparameters\030\002 \003(\0132\026.twitter.Url" +
      ".Parameter\032(\n\tParameter\022\014\n\004name\030\001 \002(\t\022\r\n" +
      "\005value\030\002 \001(\tB\036\n\020net.unto.twitterB\nUtilPr" +
      "otos";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_twitter_Url_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_twitter_Url_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_twitter_Url_descriptor,
              new java.lang.String[] { "BaseUrl", "Parameters", },
              net.unto.twitter.UtilProtos.Url.class,
              net.unto.twitter.UtilProtos.Url.Builder.class);
          internal_static_twitter_Url_Parameter_descriptor =
            internal_static_twitter_Url_descriptor.getNestedTypes().get(0);
          internal_static_twitter_Url_Parameter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_twitter_Url_Parameter_descriptor,
              new java.lang.String[] { "Name", "Value", },
              net.unto.twitter.UtilProtos.Url.Parameter.class,
              net.unto.twitter.UtilProtos.Url.Parameter.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
